### ISSUE TITLE
Unable to run middle server

### ISSUE THREAD

**Issue by lcpriest** [manastech/middleman-search#21]
I've set up a demo app with nothing but middleman-search set up:
https://github.com/lcpriest/middleman-search-demo

Any ideas what is going on?

```
=> middleman server
== The Middleman is loading
bundler: failed to load command: middleman (/Users/lcp/.rbenv/versions/2.3.3/bin/middleman)
V8::Error: Cannot call method 'apply' of null
  at t.Index.use (/Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-search-0.9.0/vendor/assets/javascripts/lunr.min.js:7:10009)
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-search-0.9.0/lib/middleman-search/search-index-resource.rb:66:in `block in build_index'
  at t (/Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-search-0.9.0/vendor/assets/javascripts/lunr.min.js:7:114)
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-search-0.9.0/lib/middleman-search/search-index-resource.rb:74:in `build_index'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-search-0.9.0/lib/middleman-search/search-index-resource.rb:29:in `render'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/rack.rb:112:in `process_request'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/rack.rb:66:in `block in call'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/rack.rb:65:in `catch'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/rack.rb:65:in `call'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/urlmap.rb:68:in `block in call'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/urlmap.rb:53:in `each'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/urlmap.rb:53:in `call'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/core_extensions/inline_url_rewriter.rb:74:in `call'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/head.rb:12:in `call'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/lint.rb:49:in `_call'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/lint.rb:37:in `call'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:153:in `call'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/mock.rb:74:in `request'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/mock.rb:56:in `get'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/extensions/asset_hash.rb:86:in `manipulate_single_resource'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/extensions/asset_hash.rb:73:in `each'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/extensions/asset_hash.rb:73:in `manipulate_resource_list'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/sitemap/store.rb:234:in `block (4 levels) in ensure_resource_list_updated!'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/notifications.rb:166:in `instrument'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/util.rb:21:in `instrument'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/sitemap/store.rb:232:in `block (3 levels) in ensure_resource_list_updated!'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/sitemap/store.rb:231:in `block (2 levels) in ensure_resource_list_updated!'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/notifications.rb:166:in `instrument'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/util.rb:21:in `instrument'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/sitemap/store.rb:224:in `block in ensure_resource_list_updated!'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/sitemap/store.rb:221:in `ensure_resource_list_updated!'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/sitemap/extensions/on_disk.rb:21:in `ready'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/callback_manager.rb:57:in `block in execute'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/callback_manager.rb:57:in `execute'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/application.rb:309:in `initialize'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/preview_server.rb:144:in `new'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/preview_server.rb:144:in `initialize_new_app'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/preview_server.rb:34:in `start'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-cli-4.2.0/lib/middleman-cli/server.rb:53:in `server'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:115:in `invoke'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:40:in `block in register'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  /Users/lcp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/middleman-cli-4.2.0/bin/middleman:70:in `<top (required)>'
  /Users/lcp/.rbenv/versions/2.3.3/bin/middleman:22:in `load'
  /Users/lcp/.rbenv/versions/2.3.3/bin/middleman:22:in `<top (required)>'
```

**Comment by matiasgarciaisaia** [comment]
Our bad!

This was solved via #19, but we didn't cut a release since then. And it's a fix so heavy it _deserves_ its own release. I'm publishing it now - thanks for the heads up!

**Comment by matiasgarciaisaia** [comment]
It's done: https://github.com/manastech/middleman-search/releases/tag/v0.10.0

Update your middleman-search version and let me know if it works for you 👍

**Comment by lcpriest** [comment]
Thanks!
